# 14.3 项目实施

In [ ]:
f = open("access.txt", "r")
access = f.read()

In [ ]:
#!/usr/bin/python
# coding: utf-8
# get 青岛地区的所有公园
import requests
import json
import csv
import pandas as pd

f = open("access.txt", "r")
def getjson(loc):
    headers = {'User-Agent' : 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1.6) Gecko/20091201 Firefox/3.5.6'} 
    for i in range(0,20):
        pa = {
            'q': '公园', 
            'region': loc,
            'scope': '2',
            'page_size': 20,
            'page_num': i,
            'output': 'json',
            'ak': access
        }
        r = requests.get("http://api.map.baidu.com/place/v2/search", params=pa, headers= headers)
        decodejson = json.loads(r.text)
        if(decodejson['results']==[]):
            return result
        test = pd.io.json.json_normalize(decodejson['results']) #flatten the json dicts
        test.columns = test.columns.map(lambda x: x.split(".")[-1])
        test.to_csv('save-files/parks-qingdao.csv',mode='a',encoding="utf8")
        print(i)
        result = decodejson
    return result


getjson('青岛市')

view = pd.read_csv('save-files/parks-qingdao.csv')
view

## 14.3.1 获取所有拥有公园的城市

In [ ]:
#!/usr/bin/python
# coding: utf-8

import requests
import json

def getjson(loc):
    headers = {'User-Agent' : 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1.6) Gecko/20091201 Firefox/3.5.6'} 
    pa = {
        'q': '公园', 
        'region': loc,
        'scope': '2',
        'page_size': 20,
        'page_num': 0, 
        'output': 'json',
        'ak': access
    }
    r = requests.get("http://api.map.baidu.com/place/v2/search", params=pa, headers= headers)
    decodejson = json.loads(r.text)
    return decodejson

province_list = ['山东省','北京市']
for eachprovince in province_list:
    decodejson = getjson(eachprovince)
    for eachcity in decodejson['results']:
     
        city = eachcity['name']
        num = getjson(city)['total']
       
        print (city, num)
        output = '\t'.join([city, str(num)]) + '\r\n'
"""        with open('cities.txt', "a+", encoding='utf-8') as f:
            f.write(output)
            f.close()
"""

In [ ]:
#!/usr/bin/python
# coding: utf-8

# 直辖市
import requests
import json
def getjson(loc):
    headers = {'User-Agent' : 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1.6) Gecko/20091201 Firefox/3.5.6'} 
    pa = {
        'q': '公园', 
        'region': loc,
        'scope': '2',
        'page_size': 20,
        'page_num': 0, 
        'output': 'json',
        'ak': access
    }
    r = requests.get("http://api.map.baidu.com/place/v2/search", params=pa, headers= headers)
    decodejson = json.loads(r.text)
    return decodejson

decodejson = getjson('全国')
six_cities_list = ['北京市','上海市','重庆市','天津市','香港特别行政区','澳门特别行政区',]
for eachprovince in decodejson['results']:
    city = eachprovince['name']
    num = getjson(city)['total']
    print(city,num)
"""    if city in six_cities_list:
        output = '\t'.join([city, str(num)]) + '\r\n'
        with open('cities.txt', "a+", encoding='utf-8') as f:
            f.write(output)
            f.close()"""

## 14.3.2 获取区域所在的区市

In [9]:

import requests
import json
import time
import csv
import pandas as pd

f = open("access.txt", "r")
access = f.read()

def getjson(loc):
    areas=[]
    districts=[]
    lat=[]
    lng=[]
    headers = {'User-Agent' : 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1.6) Gecko/20091201 Firefox/3.5.6'} 
    for i in range(0,len(loc)):

        pa = {
            'q': loc[i], 
            'region': '青岛市',
            'scope': '2',
            'page_size': 1,
            'page_num': 0,
            'city_limit':'true',
            'output': 'json',
            'coord_type':'1', 
            'ak': access
        }
        r = requests.get("http://api.map.baidu.com/place/v2/search", params=pa, headers= headers)
        decodejson = json.loads(r.text)
        #if(decodejson['results']==[]):
         #   return result
            
        print(decodejson,'\n')
        
        test = pd.io.json.json_normalize(decodejson['results']) #flatten the json dicts
        print(test)
        test.columns = test.columns.map(lambda x: x.split(".")[-1])
        valuea = loc[i]
        valuelat = test.lat
        valuelng = test.lng
        try:            
            valued = test['area']
        except:
            valued = ''

        areas.append(valuea)
        districts.append(valued)
        lat.append(valuelat)
        lng.append(valuelng)
        time.sleep(2.5)
        #test.to_csv('data/district.csv',mode='a',encoding="utf8")
        #print(decodejson,'\n')
        #print(test,'\n')
    dictn = {'areas':areas, 'districts':districts,'lat':lat,'lng':lng}
    final = pd.DataFrame.from_dict(dictn,orient='index')
        #result = decodejson
    #return test
     #   print(test)
    return final
list2 = [' 即墨', ' 香江路', ' 薛家岛', ' 李沧万达', ' 唐岛湾', ' 夏庄', ' 女姑', ' 石老人',
       ' 胶南', ' 四方实验小区', ' 错埠岭', ' 流亭', ' 新都心', ' 下王埠', ' 八大湖', ' 北仲',
       ' 十梅庵', ' 国信体育场', ' 台东', ' 东方影都', ' 镇江路', ' 理工大学', ' 海泊河', ' 团岛',
       ' 合肥路佳世客', ' 河南', ' 书院路', ' 崂山CBD', ' 金沙滩', ' 保税区', ' 北村', ' 胶州',
       ' 黄岛区政府', ' 瑞阳路', ' 中央CBD', ' 同安路', ' 枣儿山', ' 惜福镇', ' 辛安', ' 榉林公园',
       ' 远洋广场', ' 海云庵', ' 天山银海', ' 浮山后', ' 新贵都', ' 家佳源', ' 石油大学', ' 田家花园',
       ' 水清沟', ' 积米崖', ' 闫家山', ' 雕塑园', ' 大尧', ' 福州北路', ' 汽车东站', ' 河西',
       ' 农业大学', ' 福安', ' 李村公园', ' 麦岛', ' 湖岛', ' 啤酒街', ' 大沙路', ' 西镇',
       ' 沧口公园', ' 湛山', ' 北岭', ' 城阳立交', ' 绿城', ' 西姜', ' 世纪公园', ' 黄岛港',
       ' 大学路', ' 灵山卫', ' 世园会', ' 东李', ' 八大关', ' 沙岭庄', ' 天泰', ' 科技大学',
       ' 城阳实验二小', ' 东南山', ' 张村', ' 奥帆中心', ' 大港小港', ' 辛家庄', ' 五四广场',
       ' 青岛北站', ' 老鸦岭', ' 沙子口', ' 闽江路', ' 午山', ' 中山公园', ' 西韩', ' 松山后',
       ' 娄山后', ' 文登路', ' 火车站', ' 太阳城', ' 黄岛轮渡']

In [ ]:
result = getjson(list2)

In [247]:
result_tst = result.T.copy()
result_tst

,areas,districts,lat,lng
0,即墨,,"0 36.394749 Name: lat, dtype: float64","0 120.453536 Name: lng, dtype: float64"
1,香江路,"0 黄岛区 Name: area, dtype: object","0 35.978126 Name: lat, dtype: float64","0 120.177032 Name: lng, dtype: float64"
2,薛家岛,"0 黄岛区 Name: area, dtype: object","0 35.968361 Name: lat, dtype: float64","0 120.228023 Name: lng, dtype: float64"
3,李沧万达,"0 李沧区 Name: area, dtype: object",lat lat 0 36.172483 36.172992,lng lng 0 120.439694 120.4...
4,唐岛湾,"0 黄岛区 Name: area, dtype: object",lat lat 0 35.95482 35.953722,lng lng 0 120.2099 120.214328
5,夏庄,"0 城阳区 Name: area, dtype: object",lat lat 0 36.266738 36.266963,lng lng 0 120.467617 120.4...
6,女姑,"0 城阳区 Name: area, dtype: object",lat lat 0 36.263046 36.266405,lng lng 0 120.374348 120.3...
7,石老人,"0 崂山区 Name: area, dtype: object",lat lat 0 36.098725 36.096719,lng lng 0 120.475153 120.47504
8,胶南,,"0 35.852858 Name: lat, dtype: float64","0 119.85631 Name: lng, dtype: float64"
9,四方实验小区,"0 市北区 Name: area, dtype: object",lat lat 0 36.109152 36.109964,lng lng 0 120.386909 120.3...
10,错埠岭,"0 市北区 Name: area, dtype: object","0 36.102144 Name: lat, dtype: float64","0 120.391952 Name: lng, dtype: float64"
11,流亭,"0 城阳区 Name: area, dtype: object",lat lat 0 36.272988 36.273127,lng lng 0 120.39353 120.392419
12,新都心,"0 市北区 Name: area, dtype: object","0 36.115066 Name: lat, dtype: float64","0 120.397727 Name: lng, dtype: float64"
13,下王埠,"0 李沧区 Name: area, dtype: object",lat lat 0 36.185959 36.185961,lng lng 0 120.440487 120.44063
14,八大湖,"0 市南区 Name: area, dtype: object",lat lat 0 36.086131 36.086108,lng lng 0 120.396079 120.3...
15,北仲,"0 市北区 Name: area, dtype: object",lat lat 0 36.087966 36.087867,lng lng 0 120.368808 120.3...
16,十梅庵,"0 李沧区 Name: area, dtype: object",lat lat 0 36.213549 36.204773,lng lng 0 120.423643 120.4...
17,国信体育场,"0 崂山区 Name: area, dtype: object","0 36.108614 Name: lat, dtype: float64","0 120.452662 Name: lng, dtype: float64"
18,台东,"0 市北区 Name: area, dtype: object","0 36.088109 Name: lat, dtype: float64","0 120.358988 Name: lng, dtype: float64"
19,东方影都,"0 黄岛区 Name: area, dtype: object",lat lat 0 35.916811 35.917623,lng lng 0 120.117782 120.1...
20,镇江路,"0 Name: area, dtype: object","0 36.09247 Name: lat, dtype: float64","0 120.372772 Name: lng, dtype: float64"
21,理工大学,"0 市北区 Name: area, dtype: object",lat lat 0 36.10661 36.107448,lng lng 0 120.378044 120.3...
22,海泊河,"0 市北区 Name: area, dtype: object","0 36.098538 Name: lat, dtype: float64","0 120.381466 Name: lng, dtype: float64"
23,团岛,"0 市南区 Name: area, dtype: object",lat lat 0 36.05213 36.051864,lng lng 0 120.294693 120.2...
24,合肥路佳世客,"0 市北区 Name: area, dtype: object",lat lat 0 36.117157 36.116682,lng lng 0 120.419886 120.4...
25,河南,"0 即墨区 Name: area, dtype: object","0 36.352911 Name: lat, dtype: float64","0 120.48922 Name: lng, dtype: float64"
26,书院路,"0 李沧区 Name: area, dtype: object","0 36.160302 Name: lat, dtype: float64","0 120.425486 Name: lng, dtype: float64"
27,崂山CBD,"0 市南区 Name: area, dtype: object",lat lat 0 36.095675 36.095878,lng lng 0 120.400139 120.39847
28,金沙滩,"0 黄岛区 Name: area, dtype: object",lat lat 0 35.966169 35.968951,lng lng 0 120.251193 120.25971
29,保税区,"0 黄岛区 Name: area, dtype: object",lat lat 0 35.991132 35.988153,lng lng 0 120.181148 120.1...
...,...,...,...,...
70,世纪公园,"0 城阳区 Name: area, dtype: object","0 36.290159 Name: lat, dtype: float64","0 120.40654 Name: lng, dtype: float64"
71,黄岛港,"0 黄岛区 Name: area, dtype: object",lat lat 0 36.024768 36.024939,lng lng 0 120.211202 120.2...
72,大学路,"0 市南区 Name: area, dtype: object","0 36.068952 Name: lat, dtype: float64","0 120.340689 Name: lng, dtype: float64"
73,灵山卫,"0 黄岛区 Name: area, dtype: object","0 35.939269 Name: lat, dtype: float64","0 120.158067 Name: lng, dtype: float64"
74,世园会,"0 李沧区 Name: area, dtype: object","0 36.206445 Name: lat, dtype: float64","0 120.510328 Name: lng, dtype: float64"
75,东李,"0 李沧区 Name: area, dtype: object",lat lat 0 36.163754 36.164188,lng lng 0 120.445218 120.4...
76,八大关,"0 市南区 Name: area, dtype: object",lat lat 0 36.059835 36.059717,lng lng 0 120.363506 120.3...
77,沙岭庄,"0 市北区 Name: area, dtype: object","0 36.147173 Name: lat, dtype: float64","0 120.365496 Name: lng, dtype: float64"
78,天泰,"0 城阳区 Name: area, dtype: object",lat lat 0 36.225243 36.224288,lng lng 0 120.434443 120.4...
79,科技大学,"0 市北区 Name: area, dtype: object",lat lat 0 36.153381 36.155521,lng lng 0 120.394115 120.3...
80,城阳实验二小,"0 城阳区 Name: area, dtype: object","0 36.317235 Name: lat, dtype: float64","0 120.420021 Name: lng, dtype: float64"
81,东南山,"0 李沧区 Name: area, dtype: object","0 36.170498 Name: lat, dtype: float64","0 120.413301 Name: lng, dtype: float64"
82,张村,"0 崂山区 Name: area, dtype: object",lat lat 0 36.143233 36.14366,lng lng 0 120.479532 120.4...
83,奥帆中心,"0 市南区 Name: area, dtype: object",lat lat 0 36.06317 36.062185,lng lng 0 120.403491 120.4...
84,大港小港,"0 市北区 Name: area, dtype: object","0 36.081599 Name: lat, dtype: float64","0 120.324193 Name: lng, dtype: float64"
85,辛家庄,"0 市南区 Name: area, dtype: object","0 36.072099 Name: lat, dtype: float64","0 120.411284 Name: lng, dtype: float64"
86,五四广场,"0 市南区 Name: area, dtype: object",lat lat 0 36.068914 36.068139,lng lng 0 120.391559 120.3...
87,青岛北站,"0 李沧区 Name: area, dtype: object",lat lat 0 36.176092 36.175661,lng lng 0 120.382925 120.3...
88,老鸦岭,"0 李沧区 Name: area, dtype: object","0 36.160247 Name: lat, dtype: float64","0 120.473424 Name: lng, dtype: float64"
89,沙子口,"0 崂山区 Name: area, dtype: object","0 36.121535 Name: lat, dtype: float64","0 120.552763 Name: lng, dtype: float64"
90,闽江路,"0 市南区 Name: area, dtype: object","0 36.074719 Name: lat, dtype: float64","0 120.409492 Name: lng, dtype: float64"
91,午山,"0 崂山区 Name: area, dtype: object","0 36.123861 Name: lat, dtype: float64","0 120.509851 Name: lng, dtype: float64"
92,中山公园,"0 市南区 Name: area, dtype: object",lat lat 0 36.067228 36.070634,lng lng 0 120.356829 120.3...
93,西韩,"0 崂山区 Name: area, dtype: object","0 36.137475 Name: lat, dtype: float64","0 120.425684 Name: lng, dtype: float64"
94,松山后,"0 崂山区 Name: area, dtype: object",lat lat 0 36.147936 36.147343,lng lng 0 120.529667 120.5...
95,娄山后,"0 李沧区 Name: area, dtype: object","0 36.218498 Name: lat, dtype: float64","0 120.39587 Name: lng, dtype: float64"
96,文登路,"0 市南区 Name: area, dtype: object","0 36.067041 Name: lat, dtype: float64","0 120.356659 Name: lng, dtype: float64"
97,火车站,"0 市南区 Name: area, dtype: object",lat lat 0 36.070725 36.070141,lng lng 0 120.320641 120.3...
98,太阳城,"0 城阳区 Name: area, dtype: object",lat lat 0 36.312421 36.312521,lng lng 0 120.396804 120.3...
99,黄岛轮渡,"0 黄岛区 Name: area, dtype: object",lat lat 0 36.054586 36.054544,lng lng 0 120.240652 120.2...

In [277]:
#clean up the dataframe with only useful information left
for i in range(len(test1)):
    result_tst.districts[i]=str(result_tst.districts[i]).replace('\nName: area, dtype: object','').strip('0').strip(' ')
    result_tst.lat[i] = (str(result_tst.lat[i]).replace('Name: lat, dtype: float64','')
                         .replace('lat        lat\n0  ','').strip('0 ').strip('\n').split('  ')[0])
                         
    result_tst.lng[i] = (str(result_tst.lng[i]).replace('Name: lng, dtype: float64','')
                         .replace('lng         lng\n0  ','').replace('lng        lng\n0  ','').strip('0 ').strip('\n').split('  ')[0])
                         
result_tst

      areas districts        lat         lng
0        即墨       即墨区  36.394749  120.453536
1       香江路       黄岛区  35.978126  120.177032
2       薛家岛       黄岛区  35.968361  120.228023
3      李沧万达       李沧区  36.172483  120.439694
4       唐岛湾       黄岛区   35.95482    120.2099
5        夏庄       城阳区  36.266738  120.467617
6        女姑       城阳区  36.263046  120.374348
7       石老人       崂山区  36.098725  120.475153
8        胶南       黄岛区  35.852858   119.85631
9    四方实验小区       市北区  36.109152  120.386909
10      错埠岭       市北区  36.102144  120.391952
11       流亭       城阳区  36.272988   120.39353
12      新都心       市北区  36.115066  120.397727
13      下王埠       李沧区  36.185959  120.440487
14      八大湖       市南区  36.086131  120.396079
15       北仲       市北区  36.087966  120.368808
16      十梅庵       李沧区  36.213549  120.423643
17    国信体育场       崂山区  36.108614  120.452662
18       台东       市北区  36.088109  120.358988
19     东方影都       黄岛区  35.916811  120.117782
20      镇江路       市北区   36.09247  120.372772
21     理工大学       市北区   36.10661  120.378044
22      海泊河       市北区  36.098538  120.381466
23       团岛       市南区   36.05213  120.294693
24   合肥路佳世客       市北区  36.117157  120.419886
25       河南       即墨区  36.352911   120.48922
26      书院路       李沧区  36.160302  120.425486
27    崂山CBD       市南区  36.095675  120.400139
28      金沙滩       黄岛区  35.966169  120.251193
29      保税区       黄岛区  35.991132  120.181148
..      ...       ...        ...         ...
70     世纪公园       城阳区  36.290159   120.40654
71      黄岛港       黄岛区  36.024768  120.211202
72      大学路       市南区  36.068952  120.340689
73      灵山卫       黄岛区  35.939269  120.158067
74      世园会       李沧区  36.206445  120.510328
75       东李       李沧区  36.163754  120.445218
76      八大关       市南区  36.059835  120.363506
77      沙岭庄       市北区  36.147173  120.365496
78       天泰       城阳区  36.225243  120.434443
79     科技大学       市北区  36.153381  120.394115
80   城阳实验二小       城阳区  36.317235  120.420021
81      东南山       李沧区  36.170498  120.413301
82       张村       崂山区        lat  120.479532
83     奥帆中心       市南区   36.06317  120.403491
84     大港小港       市北区  36.081599  120.324193
85      辛家庄       市南区  36.072099  120.411284
86     五四广场       市南区  36.068914  120.391559
87     青岛北站       李沧区  36.176092  120.382925
88      老鸦岭       李沧区  36.160247  120.473424
89      沙子口       崂山区  36.121535  120.552763
90      闽江路       市南区  36.074719  120.409492
91       午山       崂山区  36.123861  120.509851
92     中山公园       市南区  36.067228  120.356829
93       西韩       崂山区  36.137475  120.425684
94      松山后       崂山区  36.147936  120.529667
95      娄山后       李沧区  36.218498   120.39587
96      文登路       市南区  36.067041  120.356659
97      火车站       市南区  36.070725  120.320641
98      太阳城       城阳区  36.312421  120.396804
99     黄岛轮渡       市北区  36.054586  120.240652

[100 rows x 4 columns]

In [259]:
for i,row in result_tst.iterrows():
    if result_tst.districts[i]=='':
        print(result_tst.iloc[[i]])

  areas districts        lat         lng
0    即墨            36.394749  120.453536
  areas districts        lat        lng
8    胶南            35.852858  119.85631
   areas districts       lat         lng
20   镇江路            36.09247  120.372772
   areas districts        lat         lng
31    胶州            36.270347  120.039532
   areas districts        lat        lng
35   同安路            36.114946  120.45529
    areas districts        lat         lng
53   福州北路            36.093692  120.405281

In [267]:
def fix_disticts_error(index,correct_dist):
    result_tst.districts[index]=correct_dist

In [278]:
fix_disticts_error(0,'即墨区')
fix_disticts_error(8,'黄岛区')
fix_disticts_error(20,'市北区')
fix_disticts_error(31,'胶州市')
fix_disticts_error(35,'市北区')
fix_disticts_error(53,'市北区')
result_tst

      areas districts        lat         lng
0        即墨       即墨区  36.394749  120.453536
1       香江路       黄岛区  35.978126  120.177032
2       薛家岛       黄岛区  35.968361  120.228023
3      李沧万达       李沧区  36.172483  120.439694
4       唐岛湾       黄岛区   35.95482    120.2099
5        夏庄       城阳区  36.266738  120.467617
6        女姑       城阳区  36.263046  120.374348
7       石老人       崂山区  36.098725  120.475153
8        胶南       黄岛区  35.852858   119.85631
9    四方实验小区       市北区  36.109152  120.386909
10      错埠岭       市北区  36.102144  120.391952
11       流亭       城阳区  36.272988   120.39353
12      新都心       市北区  36.115066  120.397727
13      下王埠       李沧区  36.185959  120.440487
14      八大湖       市南区  36.086131  120.396079
15       北仲       市北区  36.087966  120.368808
16      十梅庵       李沧区  36.213549  120.423643
17    国信体育场       崂山区  36.108614  120.452662
18       台东       市北区  36.088109  120.358988
19     东方影都       黄岛区  35.916811  120.117782
20      镇江路       市北区   36.09247  120.372772
21     理工大学       市北区   36.10661  120.378044
22      海泊河       市北区  36.098538  120.381466
23       团岛       市南区   36.05213  120.294693
24   合肥路佳世客       市北区  36.117157  120.419886
25       河南       即墨区  36.352911   120.48922
26      书院路       李沧区  36.160302  120.425486
27    崂山CBD       市南区  36.095675  120.400139
28      金沙滩       黄岛区  35.966169  120.251193
29      保税区       黄岛区  35.991132  120.181148
..      ...       ...        ...         ...
70     世纪公园       城阳区  36.290159   120.40654
71      黄岛港       黄岛区  36.024768  120.211202
72      大学路       市南区  36.068952  120.340689
73      灵山卫       黄岛区  35.939269  120.158067
74      世园会       李沧区  36.206445  120.510328
75       东李       李沧区  36.163754  120.445218
76      八大关       市南区  36.059835  120.363506
77      沙岭庄       市北区  36.147173  120.365496
78       天泰       城阳区  36.225243  120.434443
79     科技大学       市北区  36.153381  120.394115
80   城阳实验二小       城阳区  36.317235  120.420021
81      东南山       李沧区  36.170498  120.413301
82       张村       崂山区        lat  120.479532
83     奥帆中心       市南区   36.06317  120.403491
84     大港小港       市北区  36.081599  120.324193
85      辛家庄       市南区  36.072099  120.411284
86     五四广场       市南区  36.068914  120.391559
87     青岛北站       李沧区  36.176092  120.382925
88      老鸦岭       李沧区  36.160247  120.473424
89      沙子口       崂山区  36.121535  120.552763
90      闽江路       市南区  36.074719  120.409492
91       午山       崂山区  36.123861  120.509851
92     中山公园       市南区  36.067228  120.356829
93       西韩       崂山区  36.137475  120.425684
94      松山后       崂山区  36.147936  120.529667
95      娄山后       李沧区  36.218498   120.39587
96      文登路       市南区  36.067041  120.356659
97      火车站       市南区  36.070725  120.320641
98      太阳城       城阳区  36.312421  120.396804
99     黄岛轮渡       市北区  36.054586  120.240652

[100 rows x 4 columns]

In [281]:
result_tst.to_csv('data/qingdao-districts.csv',index=False)